set_property PACKAGE_PIN T5 [get_ports clk]
set_property PACKAGE_PIN P15 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]

set_property IOSTANDARD LVCMOS33 [get_ports {light[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {light[0]}]
set_property PACKAGE_PIN K2 [get_ports light]

set_property IOSTANDARD LVCMOS33 [get_ports _rst_n]
set_property PACKAGE_PIN V1 [get_ports _rst_n]
set_property SLEW SLOW [get_ports {light[7]}]
set_property SLEW SLOW [get_ports {light[6]}]
set_property SLEW SLOW [get_ports {light[5]}]
set_property SLEW SLOW [get_ports {light[4]}]
set_property SLEW SLOW [get_ports {light[3]}]
set_property SLEW SLOW [get_ports {light[2]}]
set_property SLEW SLOW [get_ports {light[1]}]
set_property SLEW SLOW [get_ports {light[0]}]

set_property PACKAGE_PIN K2 [get_ports lighK2]
set_property PACKAGE_PIN J2 [get_ports light2]
set_property PACKAGE_PIN J3 [get_ports light3]
set_property PACKAGE_PIN H4 [get_ports light4]
set_property PACKAGE_PIN J4 [get_ports light5]
set_property PACKAGE_PIN G3 [get_ports light6]
set_property PACKAGE_PIN G4 [get_ports light7]
set_property PACKAGE_PIN F6 [get_ports light8]
set_property IOSTANDARD LVCMOS33 [get_ports lighK2]
set_property IOSTANDARD LVCMOS33 [get_ports light2]
set_property IOSTANDARD LVCMOS33 [get_ports light3]
set_property IOSTANDARD LVCMOS33 [get_ports light4]
set_property IOSTANDARD LVCMOS33 [get_ports light5]
set_property IOSTANDARD LVCMOS33 [get_ports light6]
set_property IOSTANDARD LVCMOS33 [get_ports light7]
set_property IOSTANDARD LVCMOS33 [get_ports light8]

set_property PACKAGE_PIN K2 [get_ports light1]
set_property IOSTANDARD LVCMOS33 [get_ports light1]

set_property PACKAGE_PIN K2 [get_ports {light[0]}]
set_property PACKAGE_PIN J2 [get_ports {light[1]}]
set_property PACKAGE_PIN J3 [get_ports {light[2]}]
set_property PACKAGE_PIN H4 [get_ports {light[3]}]
set_property PACKAGE_PIN J4 [get_ports {light[4]}]
set_property PACKAGE_PIN G3 [get_ports {light[5]}]
set_property PACKAGE_PIN G4 [get_ports {light[6]}]
set_property PACKAGE_PIN F6 [get_ports {light[7]}]

set_property PACKAGE_PIN T5 [get_ports _clk]
set_property IOSTANDARD LVCMOS33 [get_ports _clk]
